services:
  node-course-mysql:
    image: mysql:9.1
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=!Mysql123
      - MYSQL_DATABASE=node_course_db
      - MYSQL_USER=node_course_dba
      - MYSQL_PASSWORD=Password123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql